apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userauth-chart.fullname" . }}
  labels:
    {{- include "userauth-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "userauth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userauth-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: USER_APP_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: userauth-config
                  key: USER_APP_SERVICE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: userauth-config
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userauth-secret
                  key: REDIS_PASSWORD
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: userauth-secret
                  key: JWT_PUBLIC_KEY
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: userauth-secret
                  key: JWT_PRIVATE_KEY