{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "order-chart.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "order-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://userauth-service.shop.svc.cluster.local:9000/v1/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/otusapp/auth/v1/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-UserId, X-Role"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}($|/)(.*)
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
      {{- end }}
  {{- end }}
  {{- end }}