apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userapp-chart.fullname" . }}
  labels:
    {{- include "userapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "userapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userapp-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: DB_PASSWORD
            - name: AMQP_HOST
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: AMQP_HOST
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: AMQP_PASSWORD
            - name: AMQP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: userapp-config
                  key: AMQP_ENABLED
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: KAFKA_HOST
            - name: KAFKA_PORT
              valueFrom:
                secretKeyRef:
                  name: userapp-secret
                  key: KAFKA_PORT
            - name: KAFKA_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: userapp-config
                  key: KAFKA_ENABLED