apiVersion: v1
kind: ConfigMap
metadata:
  name: userauth-config
data:
  USER_APP_SERVICE_URL: "http://userapp-service.order.svc.cluster.local:9000/auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: userauth-secret
type: Opaque
data:
  JWT_PUBLIC_KEY: {{ .Values.jwt.publicKey | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.jwt.privateKey | b64enc | quote }}